sudo: required
language: cpp
osx_image: xcode11.3
os:
  - osx

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

env:
  - LLVM_VERSION=6.0
  - LLVM_VERSION=7.0
  - LLVM_VERSION=8.0
  - LLVM_VERSION=9.0
  - LLVM_VERSION=10.0
  - LLVM_VERSION=11.0

script:
  - travis_wait 35 sh travis-macos.sh
