---
- name: "Install Python dependencies for LIT: lit and filecheck"
  pip:
    name:
      - lit==0.9.0
      - filecheck==0.0.11
    executable: pip3

- name: Run LIT tests (Debug)
  command: ninja tests-lit
  args:
    chdir: "{{ debug_build_dir }}"

- name: Run LIT tests (Release)
  command: ninja tests-lit
  args:
    chdir: "{{ release_build_dir }}"
