name: CI

on: [pull_request]

jobs:
  test:
    name: LLVM ${{ matrix.LLVM_VERSION }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        LLVM_VERSION: [3.9.0, 4.0.0, 5.0.0, 6.0.0, 7.0.0, 8.0.0, 9.0.0]
        os: [ubuntu-18.04, macOS-10.15]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Run macOS
        if: matrix.os == 'macOS-10.15xx'
        run: |
          pip install ansible
          cd infrastructure && \
          ansible-playbook macos-playbook.yaml \
            -e llvm_version=${{ matrix.LLVM_VERSION }} \
            -e source_dir=$PWD/.. \
            -e gitref=$GITHUB_SHA \
            -e host=localhost \
            -e skip_package=true \
            -e SDKROOT=`xcrun -show-sdk-path` \
            --verbose
      - name: Run Ubuntu
        if: matrix.os == 'ubuntu-18.04'
        run: |
          sudo ln -s /usr/include/locale.h /usr/include/xlocale.h
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          cd infrastructure && \
          ansible-playbook ubuntu-playbook.yaml \
            -e llvm_version=${{ matrix.LLVM_VERSION }} \
            -e source_dir=$PWD/.. \
            -e gitref=$GITHUB_SHA \
            -e host=localhost \
            -e skip_package=false \
            --verbose
      - name: Check package
        if: matrix.os == 'ubuntu-18.04'
        run: |
          pwd
          ls packages
      - uses: actions/upload-artifact@v1
        if: matrix.os == 'ubuntu-18.04'
        with:
          name: package
          path: packages
